#baseURL = "https://HowardHo-CFD.github.io/"
baseURL = "https://HowardHo-CFD.github.io/academic_website/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Dr. Howard Haonan Ho"
theme = "blowfish"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[about]
  layout = "page"