baseURL = "https://HowardHo-CFD.github.io/"
#baseURL = "https://HowardHo-CFD.github.io/academic_website/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Dr. Howard Haonan Ho"
theme = "blowfish"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          inline = [['$', '$'], ['\\(', '\\)']]
          block = [['$$', '$$'], ['\\[', '\\]']]

[about]
  layout = "page"