languageCode = "en"
languageName = "English"
weight = 1
title = "Dr. Howard Haonan Ho"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  description = "My awesome website"
  copyright = "© 2026 Howard Haonan Ho"
  dateFormat = "2 January 2006"

[params.author]
  name = "Dr. Howard Haonan Ho"
  image = "img/my-photo.jpg"
  #headline = "This is my website with my links"
  # bio = "A little bit about you"
   links = [
     { google-scholar = "https://scholar.google.com/citations?user=LVaDiJ0AAAAJ&hl=en" },
     { github = "https://github.com/nunocoracao/blowfish" },
     { linkedin = "https://www.linkedin.com/in/howard-haonan-ho/" },
     { youtube = "https://www.youtube.com/@HowardHo-n7i" },
     { researchgate = "https://www.researchgate.net/profile/Howard-Ho-4?ev=hdr_xprf"}
   ]