[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "About"
pageRef = "about"
weight = 10

[[main]]
name = "CV"
pageRef = "cv"
weight = 15

[[main]]
name = "Publications"
pageRef = "publications"
weight = 20

[[main]]
name = "Projects"
pageRef = "projects"
weight = 30

[[main]]
name = "Teaching"
pageRef = "teaching"
weight = 40

[[main]]
name = "Gallery"
pageRef = "gallery"
weight = 50

[[main]]
  identifier = "google_scholar"
  pre = "link"
  url = "https://scholar.google.ca/citations?user=LVaDiJ0AAAAJ&hl=en"
  weight = 40

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/HowardHo-CFD?tab=repositories"
  weight = 50

[[main]]
  identifier = "youtube"
  pre = "youtube"
  url = "https://www.youtube.com/@HowardHo-n7i"
  weight = 60