[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "Biography & CV"
pageRef = "about"
weight = 10

[[main]]
name = "Research"
pageRef = "research"
weight = 20

[[main]]
  parent = "Research"
  name = "Publications"
  pageRef = "research/publications"
  weight = 10

[[main]]
  parent = "Research"
  name = "Projects"
  pageRef = "research/projects"
  weight = 20

[[main]]
name = "Teaching"
pageRef = "teaching"
weight = 40

[[main]]
  parent = "Teaching"
  name = "Dynamics (MIE 100)"
  pageRef = "teaching/dynamics"
  weight = 2

[[main]]
  parent = "Teaching"
  name = "Fluids (MIE 312)"
  pageRef = "teaching/fluids"
  weight = 3

[[main]]
name = "Fluids Gallery"
pageRef = "gallery"
weight = 50

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 100